site_name: Creatorfy Help
site_url: https://creatorfy.com
theme:
  logo: assets/creatorfy.png
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: pink
      accent: pink 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: pink
      accent: pink
nav:
  - About us: index.md
  - Setting up Experiences: ExperienceGuide.md
  - FAQ: FAQS.md
plugins:
  - search
  - social
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/creatorfy
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/mBrr52CDXu
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/creatorfy/
copyright: |
  &copy; 2023 <a href="https://creatorfy.com/"  target="_blank" rel="noopener">Creatorfy</a>
